yf:
    account:
        appKey: 0000000
        appSecret: password
        salt: devwww
        userAccount: SBZZ
        password: a123456
        version: 1.0
    bw:
        url: http://www.buzhidaoshisha.com/router/rest
        method:
            oauth: auth