bw:
  account:
    appKey: aaaaaa
    appSecret: aaaaaa
    salt: aaaaaa
    userAccount: aaaaaa
    password: aaaaaa
    version: 1.0
  url: haaaaaa
  aes:
    password: aes
  esb:
    url:
      invoicePush: http://
ct:
  account:
    appKey: aaaaaa
    appSecurity: aaaaaa
    ticketUrl: aaaaaa